### ISSUE TITLE
A question about Loss Function：L_{PAN} 

### ISSUE THREAD

**Issue by Sandy-program** [ShyFoo/Nemesis#2]
作者你好，你这篇工作非常优秀，我对此十分感兴趣。然而，我对下面这块内容存在在一些疑惑，希望您有空能帮我解释一下。
![image](https://github.com/user-attachments/assets/fa7c938e-aeff-4af8-874d-ac9c670e028c)
这块内容的大致意思是不是：我们随机对提示进行l_N次缩放，为的就是找到Low-Norm Effect出现的那一刻（对应图中的标红的内容），而Low-Norm Effect出现的时候往往伴随着高的模型准确率（这也是文章的核心观点）。然而，我们没有办法手动触发Low-Norm Effect这种现象的出现，只能如上图所示，随机对l_N个进行缩放来指望从这些缩放中找到这个现象发生的时刻。

**Comment by ShyFoo** [comment]
> 作者你好，你这篇工作非常优秀，我对此十分感兴趣。然而，我对下面这块内容存在在一些疑惑，希望您有空能帮我解释一下。 ![image](https://private-user-images.githubusercontent.com/65120241/366404362-fa7c938e-aeff-4af8-874d-ac9c670e028c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjMyNjQsIm5iZiI6MTcyNjEyMjk2NCwicGF0aCI6Ii82NTEyMDI0MS8zNjY0MDQzNjItZmE3YzkzOGUtYWVmZi00YWY4LTg3NGQtYWM5YzY3MGUwMjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2MzYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzODAyZjM0OGU1OWI4YWZkM2Q3ZWI0YWEwZmRhMDllNTNhNzYwNWUzNDJlMTdiMmYzOGY4M2Q5Yjg2ZjA2M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ThEIo01yyYqGONcsfKv_MpO5atG63Ozsmlmrd9C9KuM) 这块内容的大致意思是不是：我们随机对提示进行l_N次缩放，为的就是找到Low-Norm Effect出现的那一刻（对应图中的标红的内容），而Low-Norm Effect出现的时候往往伴随着高的模型准确率（这也是文章的核心观点）。然而，我们没有办法手动触发Low-Norm Effect这种现象的出现，只能如上图所示，随机对l_N个进行缩放来指望从这些缩放中找到这个现象发生的时刻。

![image](https://github.com/user-attachments/assets/d7e995a4-1c13-4197-b53e-0ff0090c5d03)

你好。你说的意思大概差不多，这里更准确的含义是对一个batch内的样本的提示进行corrupt (即缩放)，实际上，在CoOp里面每个样本的提示都一样，假设提示总共有L个位置(CoOp为16)，我们可以从L个随机选N个不同的位置进行corrupt，假设corrupt之后这个batch的模型准确率上升，我们认为这时候出现了Low-Norm Effect，那么我们应该对这N个位置的提示进行normalize。

**Comment by Sandy-program** [comment]
作者你好，我大概明白您的意思了，我可以解读成这样吗？
![image](https://github.com/user-attachments/assets/502e641b-c243-4bab-9649-a5f78b54a639)

**Comment by ShyFoo** [comment]
> 作者你好，我大概明白您的意思了，我可以解读成这样吗？ ![image](https://private-user-images.githubusercontent.com/65120241/367499895-502e641b-c243-4bab-9649-a5f78b54a639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDIwOTEsIm5iZiI6MTcyNjMwMTc5MSwicGF0aCI6Ii82NTEyMDI0MS8zNjc0OTk4OTUtNTAyZTY0MWItYzI0My00YmFiLTk2NDktYTVmNzhiNTRhNjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGExMGNhMWM4NzVkZTkyNDgwOTAwYzNkNDhhNDAzOGI4YWJkYjcxZGZkOWQ1NjE1NzY2YzlmYWQ4NTZjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eN-sqmqxq7NBp0bQr1UWUD8SPMYKv-QlAA1blKjlePM)

Exactly.

**Comment by Sandy-program** [comment]
非常感谢你的帮助Thanks♪(･ω･)ﾉ
